package org.proninyaroslav.opencomicvine.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006D41)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF68FDAE)
val md_theme_light_onPrimaryContainer = Color(0xFF002110)
val md_theme_light_secondary = Color(0xFF4E6354)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFD1E8D6)
val md_theme_light_onSecondaryContainer = Color(0xFF0C1F14)
val md_theme_light_tertiary = Color(0xFF6B5E00)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFBE352)
val md_theme_light_onTertiaryContainer = Color(0xFF211C00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFDF8)
val md_theme_light_onBackground = Color(0xFF191C1A)
val md_theme_light_surface = Color(0xFFFBFDF8)
val md_theme_light_onSurface = Color(0xFF191C1A)
val md_theme_light_surfaceVariant = Color(0xFFDCE5DC)
val md_theme_light_onSurfaceVariant = Color(0xFF414942)
val md_theme_light_outline = Color(0xFF717972)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1ED)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF46E094)
val md_theme_light_surfaceTint = Color(0xFF006D41)

val md_theme_dark_primary = Color(0xFF46E094)
val md_theme_dark_onPrimary = Color(0xFF003920)
val md_theme_dark_primaryContainer = Color(0xFF005230)
val md_theme_dark_onPrimaryContainer = Color(0xFF68FDAE)
val md_theme_dark_secondary = Color(0xFFB5CCBA)
val md_theme_dark_onSecondary = Color(0xFF213528)
val md_theme_dark_secondaryContainer = Color(0xFF374B3E)
val md_theme_dark_onSecondaryContainer = Color(0xFFD1E8D6)
val md_theme_dark_tertiary = Color(0xFFDEC738)
val md_theme_dark_onTertiary = Color(0xFF383000)
val md_theme_dark_tertiaryContainer = Color(0xFF514700)
val md_theme_dark_onTertiaryContainer = Color(0xFFFBE352)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF191C1A)
val md_theme_dark_onBackground = Color(0xFFE1E3DE)
val md_theme_dark_surface = Color(0xFF191C1A)
val md_theme_dark_onSurface = Color(0xFFE1E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414942)
val md_theme_dark_onSurfaceVariant = Color(0xFFC0C9C0)
val md_theme_dark_outline = Color(0xFF8A938B)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1A)
val md_theme_dark_inverseSurface = Color(0xFFE1E3DE)
val md_theme_dark_inversePrimary = Color(0xFF006D41)
val md_theme_dark_surfaceTint = Color(0xFF46E094)


@Suppress("unused")
val seed = Color(0xFF29CC82)
